version: '3.4'

services:
  django_app:
    image: django_app
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "python manage.py migrate && python -m debugpy --wait-for-client --listen 0.0.0.0:3000 manage.py runserver 0.0.0.0:8000 --nothreading"]
    user: 0:0
    volumes:
      - ./DjangoPractice:/django_app
    ports:
      - 8000:8000
      - 3000:3000
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13-alpine
    volumes:
      - django_debug_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django-practice-db
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    ports:
      - 5432:5432
volumes:
  django_debug_postgres_data: