# Generated by Django 4.0.6 on 2022-07-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_user_creation_date_remove_user_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(verbose_name='дата рождения пользователя'),
        ),
    ]
