# Generated by Django 4.0.6 on 2022-07-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата рождения пользователя'),
        ),
    ]
