# Generated by Django 4.0.6 on 2022-07-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15, verbose_name='логин пользователя')),
                ('password', models.CharField(max_length=20, verbose_name='пароль пользователя')),
                ('photo', models.ImageField(upload_to='user_images/%Y/%m/%d/', verbose_name='аватарка пользователя')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания пользователя')),
                ('friends', models.ManyToManyField(to='personal.user')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
