# Generated by Django 4.0.6 on 2022-07-19 17:58

import apps.chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 related_name='first_user', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 related_name='second_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(
                    max_length=1024, verbose_name='текст сообщения')),
                ('sent_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='дата отсылки сообщения')),
                ('last_updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='дата изменения сообщения')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='chat.chat', verbose_name='чат, в котором будет осуществляться переписка')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.chat.models.Attachment.get_chat_directory_path,
                 verbose_name='файл, прикреплённый к сообщению')),
                ('upload_date', models.DateTimeField(
                    auto_now_add=True, verbose_name='дата загрузки файла')),
                ('file_owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
    ]
