# Generated by Django 4.0.6 on 2022-07-21 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_alter_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='first_user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='private',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='second_user',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=False, editable=False, verbose_name='Является ли чат приватным?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи в чате'),
        ),
    ]
