# Generated by Django 4.0.6 on 2022-07-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chat_is_private_remove_message_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
    ]
