# Generated by Django 4.0.6 on 2022-07-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_attachment_file_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
    ]
